# Maven stuff
GROUP=com.mikepenz
VERSION_NAME=10.0.0-b01
VERSION_CODE=10000

POM_URL=https://github.com/mikepenz/MaterialDrawer
POM_SCM_URL=https://github.com/mikepenz/MaterialDrawer
POM_SCM_CONNECTION=scm:git@github.com:mikepenz/MaterialDrawer.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:mikepenz/MaterialDrawer.git
POM_SCM_URL_ISSUES=https://github.com/mikepenz/MaterialDrawer/issues
POM_GITHUB_REPO=mikepenz/MaterialDrawer
POM_GITHUB_README=README.md
POM_LICENCE_NAME=Apache-2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=mikepenz
POM_DEVELOPER_NAME=Mike Penz
# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true
android.enableJetifier=false
org.gradle.caching=true
org.gradle.configuration-cache=false
android.suppressUnsupportedCompileSdk=34
# Dokka
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
# convention plugin
com.mikepenz.kotlin.warningsAsErrors.enabled=false